function (add_skipper_test NAME)
  get_filename_component(ABSOLUTE_PATH ${NAME}.cpp ABSOLUTE)
  if (EXISTS ${ABSOLUTE_PATH})
    message(STATUS "Adding skipper test: ${NAME}.cpp")
  else()
    message(SEND_ERROR "${ABSOLUTE_PATH} does not exist")
    return()
  endif ()

  add_executable(${NAME} test_catch2_main.cpp ${NAME}.cpp)
  target_link_libraries(${NAME} PRIVATE Catch2::Catch2)
  target_link_libraries(${NAME} PRIVATE skipper::skipper)
endfunction ()

function (add_skipper_benchmark NAME)
  get_filename_component(ABSOLUTE_PATH ${NAME}.cpp ABSOLUTE)
  if (EXISTS ${ABSOLUTE_PATH})
    message(STATUS "Adding skipper benchmark: ${NAME}.cpp")
  else()
    message(SEND_ERROR "${ABSOLUTE_PATH} does not exist")
    return()
  endif ()

  add_executable(${NAME} ${NAME}.cpp)
  target_link_libraries(${NAME} PRIVATE benchmark::benchmark_main)
  target_link_libraries(${NAME} PRIVATE skipper::skipper)
endfunction ()
